### PR TITLE
Fixes + SFML 2.3 support

### PR DESCRIPTION
**Pull request by TankOs**
Some fixes for various compiler errors and warnings (tried with Clang++ 3.6.0). Support for SFML 2.3 (ContextSettings constructor calls).

### CODE REVIEW

**Comment by binary1248** [comment]
- Get rid of the added tabs in dbeb29a031d178bcd0ca95f703bdf7729f974377.
- Add `std::` to `strrchr` in e893831a37ccf1631973227bf6b3e477a6cb0717.
- Don't just remove the line in a5f81e1694bdd41a236988938ad85e1de622b6ee, just set the default value to false. This way the entry is still visible in the default CMake configuration.

Fix those issues and this is good for a merge.

**Comment by TankOs** [comment]
> Don't just remove the line in a5f81e1, just set the default value to false. This way the entry is still visible in the default CMake configuration.

Shouldn't this actually be done in the FindSFML.cmake script? It seems weird that GLS shall setup dependency configuration values.

**Comment by binary1248** [comment]
It can't be done in FindSFML.cmake because by the time it gets called, the variable is already used. The user will not have the opportunity to set the variable unless FindSFML.cmake was already called previously and the variable added to the cache. This is also documented in FindSFML.cmake itself, so the idea is that whoever uses FindSFML.cmake ends up creating/setting that variable in their own scripts first.

**Comment by TankOs** [comment]
> the idea is that whoever uses FindSFML.cmake ends up creating/setting that variable in their own scripts first.

Exactly, when building an executable you take care of it. But IMHO not as a library in between. FindSFML.cmake should take care of setting the cache variable, not GLS' -- that's what I basically meant.

**Comment by eXpl0it3r** [comment]
It's an option for the FindSFML.cmake and it shouldn't be cached by FindSFML.cmake.

In SFGUI, Thor and other projects one just used yet another flag to then set that option in build script before finding SFML, but the temporary variable just clutters things unnecessarily.

They way it was, was good.

**Comment by TankOs** [comment]
> It's an option for the FindSFML.cmake and it shouldn't be cached by FindSFML.cmake.

I don't see a problem with it. As FindSFML.cmake provides the option, I think it would be alright if it created the option, which makes it easier for the user to change it. How you link is normally up to the user who's building the last binary in the chain (mostly an executable).

However, if you say "No, not gonna change this", I will simply add it to the PR again for a merge. It's your library in the end. :)

**Comment by eXpl0it3r** [comment]
FindSFML.cmake can't add it to the cache, because scripts that build on top of it may not want it to leak through to the cache.

**Comment by binary1248** [comment]
> As FindSFML.cmake provides the option, I think it would be alright if it created the option, which makes it easier for the user to change it.

This is like saying that a function should set one of it's own parameters. The only reason why it works in this special case is because of CMake's cache. If there was some way to disable it and make all values get repopulated every run, your suggestion would never allow the user to have control over the linkage because their setting would always get overridden.

> How you link is normally up to the user who's building the last binary in the chain (mostly an executable).

Which is why the one who's building the library gets to decide on how to link. Maybe you just misunderstood what I meant in the first place. I don't care whether that variable is set to true or false. All I care is that it is created somewhere in GLS's CMake script. The only reason why it is set to a certain value is because CMake wants it (the syntax) to be like that.

> However, if you say "No, not gonna change this", I will simply add it to the PR again for a merge.

Not gonna remove the line, just change true to false. :wink:

**Comment by TankOs** [comment]
> This is like saying that a function should set one of it's own parameters.

It's more like knowing that a function has a particular parameter and setting a _default_ value for it. FindSFML.cmake evaluates SFML_STATIC_LIBRARIES, therefore I think it's correct if it also sets the variable, just like you do in GLS. This is only for convenience, though, as in the end, the user has to choose how he wants to link.

I'm actually not even saying that GLS is doing it wrong, I rather claim that FindSFML.cmake should setup the cache variable with a default value (TRUE in this case, as that is the default if SFML_STATIC_LIBRARIES is not present).

I'm going to adjust the PR to be like you asked. :cat2:

**Comment by eXpl0it3r** [comment]
As I said: FindSFML.cmake can't add it to the cache, because scripts that build on top of it may not want it to leak through to the cache.

**Comment by TankOs** [comment]
Any particular reason for that?

**Comment by eXpl0it3r** [comment]
It's not a libraries job to tell developers how they should write their CMake scripts. Some might like to expose the option, others might like to hide it. FindSFML.cmake provides an option for the developer and not the "end user".

**Comment by TankOs** [comment]
> It's not a libraries job to tell developers how they should write their CMake scripts.

Why does GLS expose it then?

> Some might like to expose the option, others might like to hide it.

You said that before, but I wanted to ask for a reason. Because I can't think of any harm it does.

> FindSFML.cmake provides an option for the developer and not the "end user".

Isn't the end user a developer as well? ;) An example use-case: Someone is programming a game and wants to link in everything statically. So he activates all the XXX_STATIC_LIBRARIES options. If FindSFML.cmake sets it in the cache to its default value, it's for pure convenience, as it is easier to find. Not setting it at all is fine for me as well, but setting it does not harm anyone.

My main point for GLS, however, is: Don't set it at all, because -- and you literally said that yourself -- libraries shall not dictate the user. That's why I have removed the line and said this:

> It seems weird that GLS shall setup dependency configuration values.

**Comment by binary1248** [comment]
Umm... I don't know if you noticed, but GLS is a header-only library.

This whole discussion about who should set the linkage type doesn't have anything to do with GLS. I just picked static SFML linking for the examples because I felt like it. I guess we can change it to dynamic linking now since it causes less headaches for people on Linux. This is in no way related to how people end up "linking GLS" in their own applications, because well... there is nothing to link. SFML is and never was a dependency. It is only used to build the examples and can be easily replaced by SDL, GLFW, etc.

**Comment by TankOs** [comment]
:+1: :cat2:

**Comment by binary1248** [comment]
Since I just committed some stuff, don't forget to rebase. :yum:

**Comment by TankOs** [comment]
Rebased and adjustments added. :cat2:

**Comment by binary1248** [comment]
Can't you just edit the commits themselves instead of adding another commit to fix the issues? I do it all the time and don't find it too hard. :grimacing:

**Comment by eXpl0it3r** [comment]
:cat2:

**Pull request merged**
